dist: trusty
sudo: false

language: node_js
node_js:
  - "10"

addons:
  chrome: stable

cache:
  directories:
    - ./node_modules
    - ~/.cache

install:
  - npm ci

script:
  - npm run test -- --watch=false --no-progress --browsers=ChromeHeadlessCI
  - npm run cy:ci
